### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by JAntonioCoder** [SistemasTecTlaxiaco/actividad-1-infografia-JAntonioCoder#1]
https://drive.google.com/file/d/1kiA0ABVRBycSX7M1tE_NG607_im2h7KP/view?usp=sharing

**Comment by Luisangelriverosbautista** [comment]
FALTO IMAGENES RELACIONADAS EN FUERA TODO BIEN 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
